datanodes:
  hosts:
    node1:
      ansible_become: yes
      #ansible_become_password: secretpassword
    node2:
      ansible_become: yes
      #ansible_become_password: secretpassword
    node3:
      ansible_become: yes
      #ansible_become_password: secretpassword

namenodes:
  hosts:
    node1:
      ansible_become: yes
      #ansible_become_password: secretpassword
secondary_namenodes:
  hosts:
    node2:
      ansible_become: yes
      #ansible_become_password: secretpassword

jumpnodes:
  hosts:
    node1:
      ansible_become: yes
      #ansible_become_password: secretpassword
