datanodes:
  hosts:
    node1:
      ansible_become: yes
      # ansible_user: team
      #ansible_become_password: secretpassword
      #ansible_ssh_pass: secretpassword
    node2:
      ansible_become: yes
      # ansible_user: team
      #ansible_become_password: secretpassword
      #ansible_ssh_pass: secretpassword
    node3:
      ansible_become: yes
      # ansible_user: team
      #ansible_become_password: secretpassword
      #ansible_ssh_pass: secretpassword

namenodes:
  hosts:
    node1:
      ansible_become: yes
      # ansible_user: team
      #ansible_become_password: secretpassword
      #ansible_ssh_pass: secretpassword
secondary_namenodes:
  hosts:
    node2:
      ansible_become: yes
      # ansible_user: team
      #ansible_become_password: secretpassword
      #ansible_ssh_pass: secretpassword

jumpnodes:
  hosts:
    jumpnode:
      ansible_become: yes
      # ansible_user: team
      #ansible_become_password: secretpassword
      #ansible_ssh_pass: secretpassword
