---
- name: Configure hosts
  hosts: namenodes
  gather_facts: no

  tasks:
    - name: Namenode format
      ansible.builtin.shell: hdfs namenode -format
      become: yes
      become_user: hadoop
      become_method: sudo
      become_flags: '-i'

    - name: Start hdfs
      ansible.builtin.shell: start-dfs.sh
      become: yes
      become_user: hadoop
      become_method: sudo
      become_flags: '-i'
