---
- name: Configure hosts
  hosts: all

  tasks:
  - name: create user hadoop
    ansible.builtin.user:
      name: hadoop
      create_home: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

  - name: configure /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: ".*{{ hostvars[item]['ansible_hostname'] }}$"
      line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }} {{hostvars[item]['ansible_fqdn'] }}"
      state: present
    with_items: "{{ groups.all }}"

  - name: Collect ssh public keys
    shell: /bin/cat /home/hadoop/.ssh/id_rsa.pub
    register: ssh_keys
    no_log: yes

  - name: Allow passwordless SSH between all hosts
    lineinfile:
      create: yes
      dest: /home/hadoop/.ssh/authorized_keys
      state: present
      line:  "{{ hostvars[item]['ssh_keys']['stdout'] }}"
    with_items: "{{ groups['all']}}"

  - name: Scan for SSH host keys
    ansible.builtin.command: ssh-keyscan -H {{ hostvars[item]['ansible_hostname'] }}
    register: ssh_scan
    loop: "{{ groups['all'] }}"
    changed_when: false

  - name: Write the host keys to known hosts
    ansible.builtin.known_hosts:
      path: /home/hadoop/.ssh/known_hosts
      name: "{{ hostvars[item.item]['ansible_hostname'] }}"
      state: present
      key: "{{ item.stdout }}"
      hash_host: true
    with_items: "{{ ssh_scan.results }}"

  - name: Install packages
    ansible.builtin.package:
      name:
        - pdsh
        - openjdk-11-jdk
      state: latest

  - name: Fetch java_home
    shell: dirname $(dirname $(readlink -f $(which javac)))
    register: java_home
    no_log: yes

  - name: Download hadoop
    ansible.builtin.unarchive:
      src: https://dlcdn.apache.org/hadoop/common/stable/hadoop-3.4.1.tar.gz
      dest: /home/hadoop/
      remote_src: yes
      creates: /home/hadoop/hadoop-3.4.1

  - name: Configure hadoop environment variables in ~/.profile
    ansible.builtin.blockinfile:
      path: /home/hadoop/.profile
      append_newline: true
      prepend_newline: true
      block: |
        export HADOOP_HOME=/home/hadoop/hadoop-3.4.1
        export JAVA_HOME={{ java_home.stdout }}
        export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

  - name: Configure hadoop environment variables in hadoop-env.sh
    ansible.builtin.blockinfile:
      path: /home/hadoop/hadoop-3.4.1/etc/hadoop/hadoop-env.sh
      append_newline: true
      prepend_newline: true
      block: |
        export JAVA_HOME={{ java_home.stdout }}
